# yaml-language-server: $schema=https://raw.githubusercontent.com/GoogleCloudPlatform/cloud-builders/master/gcloud/cloudbuild.yaml
steps:
  # Debugging step to print variables
  - name: 'ubuntu'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "--- Debugging Info ---"
        echo "Project ID: $PROJECT_ID"
        echo "Build ID: $BUILD_ID"
        echo "Commit SHA: $COMMIT_SHA"
        echo "Short SHA: $SHORT_SHA"
        echo "----------------------"

  # Build backend image
  - name: 'gcr.io/cloud-builders/docker'
    args: 
      - 'build'
      - '--platform=linux/amd64'
      - '-t'
      - 'gcr.io/$PROJECT_ID/flujo-backend:latest'
      - './backend'
    id: 'build-backend'

  # Build frontend image  
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '--platform=linux/amd64'
      - '-t' 
      - 'gcr.io/$PROJECT_ID/flujo-frontend:latest'
      - './frontend'
    id: 'build-frontend'

  # Push backend image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/flujo-backend:latest'
    id: 'push-backend'
    waitFor: ['build-backend']

  # Push frontend image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/flujo-frontend:latest'
    id: 'push-frontend'
    waitFor: ['build-frontend']

  # Deploy backend to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'flujo-backend'
      - '--image'
      - 'gcr.io/$PROJECT_ID/flujo-backend:latest'
      - '--region'
      - 'us-south1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--add-cloudsql-instances'
      - '${PROJECT_ID}:us-south1:grupo11cashflow'
      - '--set-env-vars'
      - 'DATABASE_URL=postgresql://${_DB_USER}:${_DB_PASSWORD}@/${_DB_NAME}?host=/cloudsql/${PROJECT_ID}:us-south1:grupo11cashflow,ENVIRONMENT=production'
      - '--set-secrets'
      - 'SECRET_KEY=flujo-secret-key:latest'
      - '--memory'
      - '2Gi'
      - '--cpu'
      - '2'
    id: 'deploy-backend'
    waitFor: ['push-backend']

  # Deploy frontend to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'flujo-frontend'
      - '--image'
      - 'gcr.io/$PROJECT_ID/flujo-frontend:latest'
      - '--region'
      - 'us-south1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port'
      - '80'
    id: 'deploy-frontend'
    waitFor: ['push-frontend']

options:
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _DB_NAME: 'demoflujo'
  _DB_USER: 'arturodlg'
  _DB_PASSWORD: 'Oc%d}c8lIm:9c2\S'

images:
  - 'gcr.io/$PROJECT_ID/flujo-backend:latest'
  - 'gcr.io/$PROJECT_ID/flujo-frontend:latest' 