"""create_sales_projections_table

Revision ID: 91187644c827
Revises: 84c9d1f9abd7
Create Date: 2024-07-31 15:02:45.394602

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91187644c827'
down_revision = '84c9d1f9abd7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP VIEW IF EXISTS vista_presupuesto_mercadeo_test_proyecto_demo_full CASCADE")
    op.execute("DROP VIEW IF EXISTS vista_presupuesto_mercadeo_test_proyecto_demo_resumen CASCADE")
    op.execute("DROP TABLE IF EXISTS presupuesto_mercadeo_test_proyecto_demo_redes_sociales CASCADE")
    op.execute("DROP TABLE IF EXISTS presupuesto_mercadeo_test_proyecto_demo_canales CASCADE")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('presupuesto_mercadeo_test_proyecto_demo_canales',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nombre_canal', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('presupuesto_total', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='presupuesto_mercadeo_test_proyecto_demo_canales_pkey')
    )
    op.create_table('presupuesto_mercadeo_test_proyecto_demo_redes_sociales',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nombre_plataforma', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('presupuesto_mensual', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='presupuesto_mercadeo_test_proyecto_demo_redes_sociales_pkey')
    )
    # Recreate the views if needed, this is just an example
    op.execute("""
    CREATE VIEW vista_presupuesto_mercadeo_test_proyecto_demo_resumen AS
    SELECT 'Canales' AS categoria, SUM(presupuesto_total) AS presupuesto_total
    FROM presupuesto_mercadeo_test_proyecto_demo_canales
    UNION ALL
    SELECT 'Redes Sociales' AS categoria, SUM(presupuesto_mensual) * 12 AS presupuesto_total
    FROM presupuesto_mercadeo_test_proyecto_demo_redes_sociales;
    """)
    op.execute("""
    CREATE VIEW vista_presupuesto_mercadeo_test_proyecto_demo_full AS
    SELECT 'Canales' AS categoria, nombre_canal AS detalle, presupuesto_total
    FROM presupuesto_mercadeo_test_proyecto_demo_canales
    UNION ALL
    SELECT 'Redes Sociales' AS categoria, nombre_plataforma AS detalle, presupuesto_mensual * 12 AS presupuesto_total
    FROM presupuesto_mercadeo_test_proyecto_demo_redes_sociales;
    """)
    # ### end Alembic commands ###
