"""add_monto_abono_linea_credito_to_pagos

Revision ID: 69d1c74b8719
Revises: cac0c0965cb4
Create Date: 2024-07-31 16:06:28.273344

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '69d1c74b8719'
down_revision: Union[str, None] = 'cac0c0965cb4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pagos', sa.Column('monto_abono_linea_credito', sa.Numeric(precision=15, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pagos', 'monto_abono_linea_credito')
    # ### end Alembic commands ###
