"""create_lineas_credito_and_usos_tables

Revision ID: 1e87ee09ea29
Revises: b38cb09f63f9 
Create Date: 2024-07-27 16:27:01.233101

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1e87ee09ea29'
down_revision: Union[str, None] = 'b38cb09f63f9' # Ensure this points to the previous migration for 'add_numero_cedula_to_clientes'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lineas_credito',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('fecha_inicio', sa.Date(), nullable=False),
    sa.Column('monto_total_linea', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('monto_disponible', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('fecha_fin', sa.Date(), nullable=False),
    sa.Column('interest_rate', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('es_revolvente', sa.Boolean(), nullable=True),
    sa.Column('cargos_apertura', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('linea_credito_usos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('linea_credito_id', sa.Integer(), nullable=False),
    sa.Column('fecha_uso', sa.Date(), nullable=False),
    sa.Column('monto_usado', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('tipo_transaccion', sa.String(length=50), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('cargo_transaccion', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['linea_credito_id'], ['lineas_credito.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('linea_credito_usos')
    op.drop_table('lineas_credito')
    # ### end Alembic commands ### 